
FROM ubuntu:noble-20240114
RUN apt-get update \
  && apt-get install -y build-essential wget zlib1g-dev autoconf automake libncurses5-dev libbz2-dev liblzma-dev libssl-dev libcurl4-gnutls-dev \
  && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
RUN tar -jxf samtools-1.11.tar.bz2
WORKDIR /samtools-1.11
RUN ./configure && make && make install
RUN rm -rf samtools-1.10 samtools-1.10.tar.bz2

