
#FROM ubuntu:noble-20240114
#ENV PATH="/root/miniconda3/bin:${PATH}"
#ARG PATH="/root/miniconda3/bin:${PATH}"
#RUN apt-get update \
#    && apt-get install -y build-essential \
#    && apt-get install -y wget zip unzip \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*
#RUN wget https://repo.continuum.io/miniconda/Miniconda3-4.3.30-Linux-x86_64.sh
#RUN bash Miniconda3-4.3.30-Linux-x86_64.sh -b
#
#RUN unset PROMPT_COMMAND

FROM continuumio/miniconda3
RUN conda install -c bioconda gatk4

